language: node_js
sudo: required
node_js:
  - "lts/*"
install:
  - yarn
jobs:
  include:
    - stage: unit tests
      script: lerna bootstrap && lerna exec --scope @fluent-ui/core -- yarn test && lerna exec --scope @fluent-ui/core -- yarn codecov
