version: 2
jobs:
  build:
    docker:
      - image: node:10

    working_directory: ~/fluent-ui

    steps:
      - checkout:
          post:
            - git fetch --all

      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-

      - run: yarn install --freeze-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run: yarn bootstrap

      - run: yarn test:prod
